### ISSUE TITLE
LDFile.ReadCSV 

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#1]
LDFile.ReadCSV returns an array of items to the user. However the current implementation found in version 1.2.11.0 does not recognize the following common escape character : " commonly refereed to as double quotes. It would be most appreciated if you could implement this feature. 

Thank you.

Citations:
[RFC4180](https://tools.ietf.org/html/rfc4180)
[Wikipedia](https://en.wikipedia.org/wiki/Comma-separated_values#Standardization)

**Comment by litdev1** [comment]
Hopefully fixed ReadCSV and WriteCSV - thanks for reporting
Fixed in beta sub-release and next build (1.2.12.0)
