### ISSUE TITLE
LDTranslate.Translate Bad Requests

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#15]
Hello LitDev with the beta release of LitDev languages such as Cherokee ,Dhivehi, Guarani, and Bihari are constantly returning Bad Request error messages. This seems to be the case because [Google Translate](https://translate.google.com/intl/en/about/languages/) does not list these languages on their supported languages page.

**Comment by litdev1** [comment]
Hi, thanks for reporting this.
The new version is an attempt to do translations using google translate, after MS discontinued its API.
It appears that some languages suggested to translate don't work.  I expect you can only get the ones listed on [https://translate.google.co.uk](https://translate.google.co.uk).  I will remove the ones you mention from LitDev extension.

**Comment by 65001** [comment]
Thanks, I'm assuming you will remove all the ones that cause problems because my list is not exhaustive by any means. Thanks for the quick response as well.
