### ISSUE TITLE
[Enhancement] LDDataBase Connections

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#16]
Is there any way that you would consider exposing the database object from LDDatabase so that C# programs could use Virtual Tables or Custom Functions while still using the abstraction provided by LitDev. It could be implemented as shown below. That to my understanding would allow people to use the raw connection to add custom functions and the like.

`        
        public static IReadOnlyList<DataBase> GetDB()
        {
            return dataBases.AsReadOnly();
        }
`

**Comment by litdev1** [comment]
Hi, 
Not quite sure I understand.
As a test I added your method and uploaded as beta to test.
