### ISSUE TITLE
LDFinance Changing Provider

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#28]
Seems based on the [forum thread](https://social.msdn.microsoft.com/Forums/en-US/eeb26bf2-c2c8-431b-bd34-15af80b56f49/litdev-extension-ldfinances?forum=smallbasic&prof=required) that I misunderstood the API cap for the current provider. 

What are your thoughts on us possibly changing it to another provider based on community input (what they want to use, and what they value)? 
Any changes that we do would probably be breaking in nature unless we somehow managed to convert the data from the new provider into the same format of that of the old one.

**Comment by litdev1** [comment]
Yes, I was also thinking that since my API ran out.  These free APIs do tend to come and go - maybe look at the yahoo one that seems to be around a while.

**Comment by 65001** [comment]
I think both Google and Yahoo shut down their public facing stock API? jricestk suggested [Tiingo.com](https://www.tiingo.com/) as an alternative.

I was also thinking about what our code is doing, all it really does is a bit of the authentication and most of it is the conversion between the JSON and the Small Basic Primitive Array's. 

Do you think it makes sense to create a converter between JSON and the arrays to automate this using [JsonTextReader](https://www.newtonsoft.com/json/help/html/ReadingWritingJSON.htm)? Obviously the correct way of implementing this would be a tree and then iterate over it to create the array but it would take a bit of time. If we implemented it correctly our API code would be severely reduced to just some boiler plate calls and it has the advantage that if the upstream API shifts by adding or removing elements our code would still work.

**Comment by litdev1** [comment]
Yes, this makes sense - I assume everything json we need is in Newtonsoft?

**Comment by 65001** [comment]
Yeah, we would need to create the tree object and iterate over it ourselves though. Basically we would be creating an abstract syntax tree for the JSON using the TextReader data and converting that into the array.
