### ISSUE TITLE
LDDatabase SQLITE

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#3]
The following SQL code : 

> Create TEMP TABLE DATA (ID INTEGER PRIMARY KEY,VALUE TEXT);
> Insert into Data VALUES (1,'2');
> Select \* From Data;

Throws an exception in the Litdev engine even though when you run it [here](http://kripken.github.io/sql.js/GUI/) or on [SQLfiddle](http://sqlfiddle.com/#!5/9ce49/1) returns valid results. 

I believe it may be due to [Line 706](https://github.com/litdev1/LitDev/blob/master/LitDev/LitDev/DataBase.cs#L706) or [Line 710](https://github.com/litdev1/LitDev/blob/master/LitDev/LitDev/DataBase.cs#L710) which seems to close the database connection and hence causes any temporary tables to be dropped.

**Comment by litdev1** [comment]
Hi,
Initial comments:

1] There is a distiction between commands that alter a database and queries that just do a query on it.
2] SQLite is different from other database types and the code lines you suggest are related to ensuring commands persist in the SQLite file.
3] You are creating TEMP table DATA, not saved by command hence I don't think TEMP tables can be used with my implementation of SQLite.

So doing commands separately from queries (this is how I implemented databases) and not using TEMP table, my code below works.

dbFile = Program.Directory+"\database1.db"
File.DeleteFile(dbFile)
database = LDDataBase.ConnectSQLite(dbFile)

command = "BEGIN TRANSACTION;"
command = command + "Create TABLE DATA (ID INTEGER PRIMARY KEY,VALUE TEXT);"
command = command + "Insert into DATA VALUES (1,'2');"
command = command + "COMMIT;"
LDDataBase.Command(database,command)

result = LDDataBase.Query(database,"Select \* From DATA;","","True")
TextWindow.WriteLine(result)

**Comment by litdev1** [comment]
A bit more playing and uploaded a beta test version where SQLite works hopefully like the other database types and allows TEMP tables.  My test code is as above except:

command = command + "Create **TEMP** TABLE DATA (ID INTEGER PRIMARY KEY,VALUE TEXT);"

**Comment by 65001** [comment]
Thank you for the fix 👍 :)
