### ISSUE TITLE
LDFinances Maintainence 

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#30]
Is there any maintenance, changes, or features for LDFinances that you are aware of on the forums that ought to be implemented? My short winter break starts in a weeks time & I would probably have some spare time to work on the project.

**Comment by litdev1** [comment]
Hi sorry the late reply - I've been out of the loop for a bit since the SB forum moved - it doesn't look like much action there yet.  So as far as I know there is nothng more to report.
Perhaps post there and see if there are any suggestions?
