### ISSUE TITLE
LDWeather Proposal

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#31]
I suggest that we use https://openweathermap.org/api to create a LDWeather functionality. 
The user would have to provide an API key from the service and their free tier is 60 calls a minute and up to 1,000,000 calls a month. This would be sufficient to track 24 locations every 15 minutes for a whole month. Do you have any thoughts on this?

**Comment by litdev1** [comment]
There is already a depreciated LDWeather - the APIs keep changing - I guess they start free then change - it will always be a bit of a moving target.
So yes if you can get it going, with clear instructions for what a user needs to do then great.
Again you should advertise that it has been added with a sample.

And happy Xmas
