### ISSUE TITLE
LDGraphicsWindow.BackGroundImage doesn't work

### ISSUE THREAD

**Issue by jrmrhrb00** [litdev1/LitDev#32]
This function doesn't seem to be working at this time.  It gives the error "Object reference not set to an instance of an object"

picture=ImageList.LoadImage("c:\temp\image.jpg")
LDGraphicsWindow.backgroundimage(picture)
GraphicsWindow.DrawImage(picture,0,0)

I just put a picture in "c:\temp" to test. If I use the ommand graphicswindow.drawimage it works just fine.

**Comment by litdev1** [comment]
A  bit late.

The GraphicsWindow needs to be created first so its background can be modified.

GraphicsWindow.Show()
picture=ImageList.LoadImage("c:\temp\image.jpg")
LDGraphicsWindow.backgroundimage(picture)
