### ISSUE TITLE
Litdev website not working

### ISSUE THREAD

**Issue by 1xxxxxxxxx** [litdev1/LitDev#35]
This is what happened:
![Capture](https://user-images.githubusercontent.com/79261564/209431604-5a1b1d6c-b4d4-441f-a990-db0bfbe4d437.PNG)
Any ideas? Is this beacause where I'm living?

**Comment by 65001** [comment]
The website registration has expired according to [ICANN](https://lookup.icann.org/en/lookup). @litdev1 hasn't done much activity on Github since around December of 2020. I can reach out to him to see if he's doing alright or something if I can find his email address. 

Is there anything I can help you with the in the meantime?

**Comment by mknierman** [comment]
I would like to know what I can do to help.  The LitDev resource has been incredibly helpful to me over the years.  It would be a shame to see this disappear from the web and deprive the next generation the advantages of MS small basic and Litdev.

**Comment by 65001** [comment]
@1xxxxxxxxx @mknierman I have created a [fork](https://github.com/65001/LitDev) and will attempt to salvage what I can from the old website to the [wiki](https://github.com/65001/LitDev/wiki). 

Any help in communicating these changes to the Small Basic community would be welcome along with contributions moving stuff from the [old website](https://web.archive.org/web/20220120132204/http://litdev.co.uk/).

**Comment by litdev1** [comment]
Hi,

Yes the website domain name lapsed and would be quite expensive to reinstate ~ $100.

The intension of the litdev extension an later the SBPrime IDE was to encourage programming and nudge people towards full featured programming languages and IDEs such as Visual Studio.
As such, the litdev extension and IDE I feel were pretty much complete - most issues arising from external APIs that kept changing or stopped being free.

Also, I got a bit fed up with microsoft's lack of support for Small Basic - principally failing to maintain it at all and then closing MSDN with the forum.  Without a forum or community there didn't seem much point to it.

All of the code I created is in github and I have a backup of the lapsed website and all of its downloads, as well as a large backlog of Small Basic code.

If there is a Small Basic community out there I am very happy to contribure and help where I can.

Glad you guys are still there...

**Comment by litdev1** [comment]
Static version of website added to guthub ([litdev1.github.io](http://litdev1.github.io)).  php and ftp not available so downloads don't work, but they are all there in downloads folder.

To get properly going again would need website hosting and some changes e.g. for extension installer new domain unless there this sufficient community to warrant reinstating litdev.co.uk.

**Comment by mknierman** [comment]
LitDev,

Great to communicate with you after all these years using your extension.  First off, thank you for your awesome extension.  It made small basic way more than a curiosity.  I grew up programing on a TI-994A in front of my TV and saving to a cassette tape recorder.  My path did not lead me to studying programming, but I found that having knowledge of programming helped me write small useful programs.  I had been looking for a something to easily make a native windows program and small basic was it but limited until I found your extension.  I have dipped my foot into writing a very simple SB extension using your example templates but did not get very far.  
I am grateful to the website you made.  It is very much in the spirit of education.  Maybe we could continue the community on your website?  For the cost of the domain, is that $100/ year?  Would you still be up for working on this?

I am unsure of why Microsoft is not supporting this.  Was not having cross platform programs an issue for adoption?  I would like to talk to Ed Price about the history and future of small basic.  You can contact me at my email address if you want to talk more off line.

Mike

**Comment by litdev1** [comment]
Mike and Abhishek,

Thanks for your kind words.

I guess the main issue with Small Basic is the fragmented user community which I am unsure how we can re-engage without MS involvement.  Frankly, I can't see any consistent forum for Small Basic users, just MS learn Q&A whic has no specific area for SB, just the very occasional random question on it.

I can restart my website, but it was basically just a portal for various resources I had accumulated which can be made available in any way if we can find the right audience.  Perhaps a more enduring approach on github or similar may be better so that others can contribute and extend may be a better long term approach.

I think MS had some issue with the legal status of the codebase left by the original Small Basic developer (Vijaye Raji), although they (Ed Price) never actually said that.  The upshot was that they didn't update SB after Vijaye left MS and kept trying and failing to recreate it as web service, which never made any sense to me.

So from my point of view I want to find a way to engage with the Small Basic community if such a thing exists and see how we can help them - perhaps we can involve Nonki Takahashi as well if we can find him.

Regards, Steve

**Comment by 65001** [comment]
@nonkit Is his GitHub handle & we can probably send him an email.

**Comment by nonkit** [comment]
I'm here.

**Comment by 65001** [comment]
Any thoughts on how to resolve the issues LitDev highlighted? I think the main point is there's a lack of a forum anymore?

**Comment by litdev1** [comment]
Hi Nonki,
Good to hear from you!
Do you know if there is any active SB community on any social media platform or any other SB related interaction with MS over the last few years, like how many downloads SB has or blog hits etc indicating there are active users out there somewhere.
If we can identify them then we should be able to point them to a common location we can use or create to kickstart SB a bit.

**Comment by mknierman** [comment]
Hi Nonki,
I want to thank you for your activity over the years. I have seen your name
frequently.  Do you know the future of small basic at Microsoft?  Will they
still actively support it going forward?
Mike

**Comment by litdev1** [comment]
We will also need to identify someone at microsoft that is at least aware of SB, thinks it is worthwhile  and is happy to be a contact for basics like updating official SB website.

**Comment by 65001** [comment]
The website is on GitHub & we can make PR's to it, if that's what we want to do.

**Comment by litdev1** [comment]
We will need someone at MS who is monitoring to accept Pull Requests for website (probably unlikely), so I think we first need an MS contact who is interested, assuming there are users out there.

So I think we need:

1] Identify that there are users out there
2] Find a receptive contact in MS (maybe Liz Bander)
3] Set up a forum with some of us including any other past SB users we can find who are prepared to help run and publicise it

**Comment by nonkit** [comment]
Recently I have never receive any information about Small Basic from Microsoft.  My understanding is that currently there is no one who can maintain Small Basic roadmap in Microsoft...

I agree with LitDev's idea above.

**Comment by nonkit** [comment]
I guess the most active community about Small Basic is https://www.facebook.com/groups/smallbasic .

**Comment by 65001** [comment]
@litdev1 Any thoughts on adding the previous releases from the website as releases on the repo, and changing the website download link to point to this repo?

Example: https://github.com/65001/LitDev/releases

**Comment by mknierman** [comment]
It looks like there are people asking about the LitDev repository recently
on the Facebook group

**Comment by litdev1** [comment]
@65001 I uploaded the entire content of the website with all resources and download [here](https://github.com/litdev1/litdev1.github.io).  This includes all the previous version downloads and everything else.  It doesn't operate on git as a website with php handling links and dowloads, but everything is there.  Please feel free to use any of it you like such as the previously released versions to make it available or point people to it.

@nonkit @mknierman I don't use facebook, but glad to hear there is some activity there.  At the moment here on github is the repository for all things litdev, so I guess point anyone to it if they are looking for specific content.

**Comment by Rupert28** [comment]
Hi guys,

First off, thanks @litdev1 so much for creating and maintaining LitDev, it's an awesome extension that I've used throughout school to supplement SB and make it heaps easier to achieve complex programs and games.

I just wanted to suggest that maybe @litdev1 could update the readme file on the GitHub page to explain what happened to the website, but more importantly have a list of each of the functions and what they do (the one that used to be on the original website). I noticed you made a static page for this, so maybe a link there that says 'Documentation:'.

Also, there are a few links on the page that go to the dead website, so maybe they could be updated.

I know there are plenty of schools and classrooms around the world that use this extension, so keeping it available and easy to access for the community would be great:)

Thanks again for an excellent project!

**Comment by litdev1** [comment]
Working on reinstating website, will be litdev.uk, since litdev.co.uk domain name is too expensive for me.

**Comment by litdev1** [comment]
For any of you that may be interested, I am in the early stages of tinkering with a new forum, mainly for my entertainment at the moment.

If it looks OK and some of you are willing to help moderate, answer etc I will advertise a bit more.

My hosting plan has a max size of 50GB, and I don't want to start something that has to close soon, so may have to limit images etc.

Anyway it is at [SBForum](https://litdev.uk/mybb)

Feedback welcome

**Comment by litdev1** [comment]
Been doing a bit of a search for where SB is being used and looks like Facebook is the most active.  FB isn't something I've used, but will engage with it.  Not so many younger basic learners, but plenty of more advanced graphics stuff.  I think there is still a gap for the primary audience of children and beginners to get advice and encouragement.

**Comment by Rupert28** [comment]
I've registered on the website, but I haven't received the activation email.

**Comment by litdev1** [comment]
> I've registered on the website, but I haven't received the activation email.

Thanks for registering, I'm not sure why MyBB didn't send activation email.  I have activated what I think is your registration.  I am new to how MyBB works, so we will see how it goes from here. 😏
