### ISSUE TITLE
App/SB/Windows hang using Shapes.Move on TextBox in LDEvents.Resized w/ GraphicsWindow 

### ISSUE THREAD

**Issue by sjsepan3** [litdev1/LitDev#37]
When resizing GraphicsWindow and moving controls with Shapes.Move, App locks up, and must restart windows.

What follows is a series of tests (5), where 1-4 are ok, and 5 exhibits error:
=====1========
Minimal app, LitDev Extensions libs not enabled in lib folder (renamed)

no error
--------------

```
GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint 
BackgroundColor better
GraphicsWindow.Height = 600

'-------Controls---------

'LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  'resize client area and controls 
  'Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
EndSub
```

=====2==========
Minimal app, LitDev Extensions libs enabled in lib folder (not renamed)

no error
--------------

```
GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint 
BackgroundColor better
GraphicsWindow.Height = 600

'-------Controls---------

'LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  'resize client area and controls 
  'Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
EndSub
```

=====3==========
Minimal app, LitDev Extensions libs enabled in lib folder (not renamed), resize event wired

no error
--------------

```
GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint 
BackgroundColor better
GraphicsWindow.Height = 600

'-------Controls---------

LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  'resize client area and controls 
  'Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
EndSub

```
=====4==========
Minimal app, LitDev Extensions libs enabled in lib folder (not renamed), resize event wired, control added

no error
--------------

```
GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint 
BackgroundColor better
GraphicsWindow.Height = 600

'-------Controls---------

txtStatusMessage = Controls.AddTextBox(0, GraphicsWindow.Height-25)

'-------Events---------

LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  'resize client area and controls 
  'Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
EndSub
```
=====5================
Minimal app, LitDev Extensions libs enabled in lib folder (not renamed), resize event wired, control added, and 
control moved

error
--------------------

```
GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint 
BackgroundColor better
GraphicsWindow.Height = 600

'-------Controls---------

txtStatusMessage = Controls.AddTextBox(0, GraphicsWindow.Height-25)

'-------Events---------

LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  'resize client area and controls 
  Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
EndSub
```
  
===============

**Comment by sjsepan3** [comment]
Windows 7 SP1, in VirtualBox 6.1.38.153438 on Linux Mint 21.2
SmallBasic 1.2
LitDev Extensions 1.2.24.0

**Comment by sjsepan3** [comment]
In summary, tests seem to indicate that:
- there is no error while dragging resize handles on GraphicWindow while LitDev not enabled, 
- nor when LitDev enabled, 
- nor when  resize event wired to handler (no control), 
- nor when control exists (not moved); 
- only when control finally moved in event handler.

**Comment by litdev1** [comment]
Hi,

Hard to to trace the exact issue, but clearly related to the window size and shape move update on the event thread - these are all actually performed on the UI thread that is called after the event ends.

For me, when it crashes I can kill the SB program with task manager using Ctrl+Alt+Del.

Small Basic does suffer from this and many similar thread event issues and the solution I have always suggested is based on setting flags in events and doing the UI work on the main UI thread in a game or event handler loop, which is closer to how more advanced languages (C# etc) do it, using a dispatcher that would send it to an queue on the UI main thread.

See [here](https://social.technet.microsoft.com/wiki/contents/articles/22264.small-basic-threading.aspx), nearly 10 years old now, but still how I would do it, ZWDZ741.000

Could ask this kind of question [here](https://litdev.uk/mybb/forumdisplay.php?fid=3), trying to get some content going!

**Comment by sjsepan3** [comment]
Reading through the TechNet article now,  to see what they are recommending...Looks like non re-entrancy plus multiple Resize events could be at play...

I was hoping that the following might work...

```

GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint BackgroundColor better
GraphicsWindow.Height = 600
onResizeActive = "False"

'-------Controls---------

txtStatusMessage = Controls.AddTextBox(0, GraphicsWindow.Height-25)

'-------Events---------

LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  If onResizeActive = "False" Then
    onResizeActive = "True"
    'resize client area and controls 
    Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
    onResizeActive = "False"
  EndIf
EndSub

  ```
...but it does not -- probably because the events come in too fast for the first one to get the flag set in time.

I will have to try the loop...

**Comment by sjsepan3** [comment]
@litdev1  Using the loop example in the TechNet article, I modified the test code as follows:
```

GraphicsWindow.Width = 800 'set before adding controls w/ positions based on size; also seems to paint BackgroundColor better
GraphicsWindow.Height = 600
onResizeActive = "False"

'-------Controls---------

txtStatusMessage = Controls.AddTextBox(0, GraphicsWindow.Height-25)

'-------Events---------

LDEvents.Resized = GraphicsWindow_OnResized

'-----------Init----------

GraphicsWindow.Show()

While ("True")
  If onResizeActive = "True" Then
    onResizeActive = "False"
    'resize client area and controls 
    Shapes.Move(txtStatusMessage, 0, GraphicsWindow.Height-25)
  EndIf
  Program.Delay(20)
EndWhile
'------------Event Handlers---------------

Sub GraphicsWindow_OnResized
  onResizeActive = "True"
EndSub
  
```
This is working so far...

**Comment by litdev1** [comment]
@sjsepan3
Great, that is what I would do, similar to the SB import link I gave (ZWDZ741.000).
The event loop idea solves many SB issues, especially with interactive games.
If you google for 'game event loop' you will see it is a totally standard way of handling events.

**Comment by sjsepan3** [comment]
@litdev1 
I was wondering what that code  was -- hadn't used that feature. 
I also applied the event-loop approach to the project from which this test version was distilled, and it worked there too, so I think _we can close this issue_, as that seems to be the right method. 
Thanks for steering me in the right direction!
