### ISSUE TITLE
Question about Attaches in Sqlite and Litdev

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#4]
In SQLITE there is the ability to attach a in memory database using 
`ATTACH DATABASE 'file::memory:' AS aux1;`
Is there a way to query that new database using Litdev extension?
Thanks in advance

**Comment by litdev1** [comment]
I don't know, only ever used file based SQLite.

**In memory DB must be used in the same process it was created**, so if created in SB, it should?

If not just use a file - I doubt there is much performance difference, but I don't know what you are doing with it.

**Comment by 65001** [comment]
You know the syntax of `LDDatabase.Command(Database,Command)` , how would you reference the newly attached database in that context

**Comment by litdev1** [comment]
Database must be the created database (file or memory) in the same process, i.e. by LDDataBase.ConnectSQLite, presumably using LDDataBase.Connection for in memory.

I've never tried, so do you have a small SB sample with in memory DB?

**Comment by 65001** [comment]
`LDDataBase.Connection = "Data Source=:memory:;Version=3;New=True;"
'database = LDDataBase.ConnectSQLite("") `
That is the closest to a memory database I could achieve, don't know if that's a real memory database or if using "" to the connect just creates a temp file somewhere....

**Comment by litdev1** [comment]
LDDataBase.Connection over-rides the connection file, so LDDataBase.ConnectSQLite("") works for me.

LDDataBase.Connection = "Data Source=:memory:;Version=3;New=True;"
database = LDDataBase.ConnectSQLite("")
...

**Comment by 65001** [comment]
So by using the LDDataBase.Connection you can force it to make a in memory database ?

**Comment by litdev1** [comment]
Yes try it I just did in my LDDataBase.sb sample replacing:

datFile = Program.Directory+"\database.db"
database = LDDataBase.ConnectSQLite(datFile)

with:

LDDataBase.Connection = "Data Source=:memory:;Version=3;New=True;"
database = LDDataBase.ConnectSQLite("")

**Comment by 65001** [comment]
Could you make it a function of `LDDataBase` ? Also is `LDDatabase.Connection` persistent over multiple database connections ?

**Comment by litdev1** [comment]
LDDatabase.Connection is a property (just a string) default is "" (unused).  You can update it any time so is persistent until you change it.

**Comment by 65001** [comment]
Okay, thanks for the help!
