### ISSUE TITLE
[REQUEST] RSA Support

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#5]
RSA or another Public-key cryptography encryption support added to the library would be really helpful and possibly aid in the overall security of programs that are possible to be created using the library.

Separate question : Which license is the entirety of this library licensed under?

**Comment by litdev1** [comment]
Will look at RSA at some point - thanks for the suggestion

The library has some bits in it from various sources with their own license e.g. box2D.  All are open source and pretty relaxed.

The litdev parts (written specifically by me in namespace LitDev) are open source using [GNU General Public License](http://www.gnu.org/licenses/gpl.html).  Basically it can be used, modified etc in any way for any use, but must remain open source - you should make any source changes available with any distribution you provide and keep it licenced as open source.

**Comment by litdev1** [comment]
Thanks for the RSA suggestion - I will look at this sometime.

The litdev extension uses seveal 3rd party codes e.g. Box2D and they have their own licensing - all open source and pretty relaxed.

Everything I wrote in namespace LitDev is licensed under [GNU General Public License](http://www.gnu.org/licenses/gpl.html).  This basically means it can be used modified in any way but must remain open source and licensed as such, i.e. provide source with any distribution and keep licenses unchanged, just as I did using other software inside this extension.

**Comment by litdev1** [comment]
New beta uploaded with basic RSA support in LDEncryption

**Comment by 65001** [comment]
Thank you so much for the quick implementation of RSA. I'll try & make my secure chat server now.

**Comment by litdev1** [comment]
Its just the basics - my test code below - if you want more features supported by .Net it should be easy to add 

```
data = "Hello World"

private = LDEncryption.RSAPrivateKey
public = LDEncryption.RSAPublicKey
'TextWindow.WriteLine(private)
'TextWindow.WriteLine(public)

LDEncryption.RSAReset()
LDEncryption.RSAPublicKey = public
encrypt = LDEncryption.RSAEncrypt(data)
TextWindow.WriteLine(encrypt)

LDEncryption.RSAReset()
LDEncryption.RSAPublicKey = private
decrpyt = LDEncryption.RSADecrypt(encrypt)
TextWindow.WriteLine(decrpyt)
```
