### ISSUE TITLE
LDControls Feature Request

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#9]
Can you implement a LDcontrols.LastListViewColumn or the like? 
Thanks in advance.

**Comment by litdev1** [comment]
You only select a row with listview, perhaps datagrid is a better option.
It may be possible, but is non trivial
[LINK](https://social.msdn.microsoft.com/Forums/vstudio/en-US/260f443e-331c-4fa4-8b1e-ad5a2fbe2f2a/how-to-select-a-column-in-a-wpf-listview?forum=wpf)

**Comment by 65001** [comment]
Would the Listview.ColumnClick event in System.Windows.Forms not work? I was trying to implement it that way but I got stuck...

I was just hoping there was a a way to either capture the column index or make it sort (ascending or descending) when the column header is clicked.

**Comment by litdev1** [comment]
The listview is using wpf not windows forms.
But I think I can get it to work by testing mouse position on preview mouse down event.
Beta test build with this as a test uploaded - it gets the column index as well as row index (not on header click - only on the data cells)
To sort on a column header click try using DataView - it is more powerful for this kind of thing than ListView

**Comment by 65001** [comment]
Okay , I will try it & get back to you.

**Comment by litdev1** [comment]
Extended to handle header clicks for listview

**Comment by 65001** [comment]
Okay so I was testing it and noticed something...

- The LDDatabase.AddListview and LDControls one's don't work the same?
- The header event doesn't fire unless you already have interacted with the ListView (by clicking on something in the ListView)

Other than that it works wonderfully. Thanks for the help, I can get to making my UI a bit more user friendly.

**Comment by litdev1** [comment]
The LDDatabase version is separate, but I have modified so that it now subscribes to the LDControls selection and header click events
A new beta version uploaded

**Comment by 65001** [comment]
Thanks for the changes.
